[client]
# Не показва грешки на потребителя
showErrorDetails = "none"

[server]
# Позволява обработка на локални файлове
enableStaticServing = "True"

[theme]
# Конфигурация на основния изглед
primaryColor = "#74512D"
borderColor = "#74512D"
backgroundColor = "#F8F4E1"
secondaryBackgroundColor = "#EFEEEA"
linkColor = "#0118D8"
codeBackgroundColor = "#547792"
font="sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseRadius = "medium"
baseFontSize = 16

[theme.sidebar]
# Конфигурация на страничния панел
primaryColor = "#74512D"
borderColor = "#74512D"
backgroundColor = "#b5dbf3"
secondaryBackgroundColor = "#AFDDFF"
codeBackgroundColor = "#547792"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
baseRadius = "small"